name: Sincronizar Links do Notion

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  atualiza-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          # Baixa o histórico completo para o robô não se perder nas versões
          fetch-depth: 0 

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar biblioteca requests
        run: pip install requests

      - name: Executar script de extração
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python atualiza_links.py

      - name: Salvar e enviar (Auto Commit)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: atualiza lista de links via Notion API"
          file_pattern: 'links.json'
